"""Add created_by, updated_by to association table

Revision ID: 1d04544e7b05
Revises: d603b3ef8585
Create Date: 2023-05-24 10:09:35.605038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d04544e7b05'
down_revision = 'd603b3ef8585'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_symptom', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('business_symptom', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('business_symptom', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('business_symptom', sa.Column('updated_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_symptom', 'updated_by')
    op.drop_column('business_symptom', 'created_by')
    op.drop_column('business_symptom', 'updated_at')
    op.drop_column('business_symptom', 'created_at')
    # ### end Alembic commands ###
