"""move diagnostic field to association table

Revision ID: 50895e6d8101
Revises: 1d04544e7b05
Create Date: 2023-05-24 10:17:40.207402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50895e6d8101'
down_revision = '1d04544e7b05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_symptom', sa.Column('diagnostic', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_symptom', 'diagnostic')
    # ### end Alembic commands ###
